HIPP-103: Api Policy Conditions
hmrc/api-hub-frontend pull request #111
Opened 2023-10-04 12:28 UTC by llmikeyj

2023-10-05 10:54 UTC, PaulCDurham requested changes

2023-10-05 10:54 UTC, PaulCDurham commented on conf/app.routes
> +POST       /apis/add-an-api/changeAPIPolicyConditionsDeclarationPage           controllers.ApiPolicyConditionsDeclarationPageController.onSubmit(mode: Mode = CheckMode)
URL for normal mode: /api-hub/apis/add-an-api/review-policy
URL for change mode: /api-hub/apis/add-an-api/change-review-policy

The scaffold adds the URLs based on lower camel case class name. HMRC Digital policy is to use all lower case with words separated by hyphens.

2023-10-05 10:54 UTC, PaulCDurham commented on app/controllers/APIPolicyConditionsDeclarationPageController.scala
> +class ApiPolicyConditionsDeclarationPageController @Inject()(
Class and file name mismatch. Could you change file name to match class name?

2023-10-05 10:54 UTC, PaulCDurham commented on test/controllers/ApiPolicyConditionsDeclarationPageControllerSpec.scala
> +        .thenReturn(Future.successful(Seq(application)))
Are there actually calls to getUserApplications?

2023-10-05 10:54 UTC, PaulCDurham commented on test/controllers/ApiPolicyConditionsDeclarationPageControllerSpec.scala
> +        .thenReturn(Future.successful(Seq(application)))
Are there actually calls to getUserApplications?

2023-10-05 10:54 UTC, PaulCDurham commented on test/controllers/ApiPolicyConditionsDeclarationPageControllerSpec.scala
> +
Could you add a test that the answer is set in the repo? The select application and select endpoints controller specs have examples. That's missing from the scaffold tests but I like to add it in.

2023-10-05 13:46 UTC, llmikeyj commented on conf/app.routes
> +POST       /apis/add-an-api/changeAPIPolicyConditionsDeclarationPage           controllers.ApiPolicyConditionsDeclarationPageController.onSubmit(mode: Mode = CheckMode)
Ok

2023-10-05 13:46 UTC, llmikeyj commented on app/controllers/APIPolicyConditionsDeclarationPageController.scala
> +class ApiPolicyConditionsDeclarationPageController @Inject()(
Ok

2023-10-05 13:46 UTC, llmikeyj commented on test/controllers/ApiPolicyConditionsDeclarationPageControllerSpec.scala
> +        .thenReturn(Future.successful(Seq(application)))
Ok

2023-10-05 13:46 UTC, llmikeyj commented on test/controllers/ApiPolicyConditionsDeclarationPageControllerSpec.scala
> +        .thenReturn(Future.successful(Seq(application)))
Ok

2023-10-06 08:00 UTC, PaulCDurham approved these changes

2023-10-06 08:46 UTC, merged