Hipp 768 request production access
hmrc/api-hub-frontend pull request #137
Opened 2023-11-14 13:24 UTC by llmikeyj

2023-11-15 10:47 UTC, edgarjimenez commented on app/views/application/RequestProductionAccessView.scala.html
> +                        @{applicationApi.apiDetail.title} usage policy
As per our conversation irl, the styling here is not quite correct

2023-11-15 11:01 UTC, PaulCDurham requested changes
Maybe look back over the view and compare it closely to the prototype. Have you reviewed that with JP?

2023-11-15 11:01 UTC, PaulCDurham commented on app/views/application/RequestProductionAccessView.scala.html
> +            ButtonViewModel(messages("requestProductionAccess.button.accept"))
Prototype and Jira ticket specify "Continue" not "Accept"

2023-11-15 11:08 UTC, PaulCDurham commented on app/views/application/RequestProductionAccessView.scala.html
> +}
Or maybe even summary.getOrElse(description.getOrElse(""))? They're both Option. So favour summary if present. Maybe ask JP

2023-11-16 11:26 UTC, PaulCDurham approved these changes

2023-11-16 11:29 UTC, edgarjimenez approved these changes

2023-11-16 11:30 UTC, merged