Hipp 869 provide supporting information page
hmrc/api-hub-frontend pull request #140
Opened 2023-11-20 15:10 UTC by llmikeyj

2023-11-20 16:07 UTC, PaulCDurham requested changes
Couple of missing tests and some trivial stuff

2023-11-20 16:07 UTC, PaulCDurham commented on test/controllers/application/ProvideSupportingInformationControllerSpec.scala
> +//    userAnswers.set(RequestProductionAccessPage, Set(Accept)).toOption.value
Remove this?

2023-11-20 16:07 UTC, PaulCDurham commented on test/controllers/application/ProvideSupportingInformationControllerSpec.scala
> +  }
Add a test to show that the page display correctly when the question has already been answered (ie filling the form from user answers works)

2023-11-20 16:07 UTC, PaulCDurham commented on test/controllers/application/ProvideSupportingInformationControllerSpec.scala
> +
Add a test to show that an invalid submission has a 400 Bad Request response (ie filing the form using formWithErrors)

2023-11-20 19:30 UTC, llmikeyj commented on app/controllers/application/RequestProductionAccessController.scala
> +            Console.println(s"formWithErrors: $formWithErrors")
Ok

2023-11-20 19:30 UTC, llmikeyj commented on test/controllers/application/ProvideSupportingInformationControllerSpec.scala
> +class ProvideSupportingInformationControllerSpec extends SpecBase with MockitoSugar with TestHelpers with HtmlValidation {
Ok

2023-11-20 19:30 UTC, llmikeyj commented on test/controllers/application/ProvideSupportingInformationControllerSpec.scala
> +//    userAnswers.set(RequestProductionAccessPage, Set(Accept)).toOption.value
Ok

2023-11-20 19:30 UTC, llmikeyj commented on test/controllers/application/ProvideSupportingInformationControllerSpec.scala
> +  }
Ok

2023-11-21 14:29 UTC, PaulCDurham approved these changes

2023-11-21 14:42 UTC, merged