Hipp 870 request production access success
hmrc/api-hub-frontend pull request #141
Opened 2023-11-23 17:23 UTC by llmikeyj

2023-11-24 10:46 UTC, PaulCDurham commented on app/controllers/application/RequestProductionAccessEndJourneyController.scala
> +        val accessRequestApis = applicationApis.map(applicationApi => {
I think we need some filtering here. If we go through multiple loops of add API/add endpoints etc then we don't always want to add all endpoints of all APIs.

applicationApis.filter(_.endpoints.exists(_.primaryAccess == Inaccessible)).map(... etc etc

2023-11-24 10:48 UTC, PaulCDurham commented on app/controllers/application/RequestProductionAccessEndJourneyController.scala
> +          val accessRequestEndpoints = applicationApi.endpoints.map(endpoint => AccessRequestEndpoint(endpoint.httpMethod, endpoint.path, endpoint.scopes))
Similarly we only want inaccessible endpoints.

applicationApi.endpoints.filter(_.primaryAccess == Inaccessible).map(... etc

2023-11-24 11:36 UTC, llmikeyj commented on app/controllers/application/RequestProductionAccessEndJourneyController.scala
> +        val accessRequestApis = applicationApis.map(applicationApi => {
These apis are generated using the same code as for the request production access page; see 

RequestProductionAccessController
```

Is this also wrong?
```

2023-11-27 12:10 UTC, PaulCDurham requested changes
One thing to fix, one question for the review with Jonathon

2023-11-27 12:10 UTC, PaulCDurham commented on app/views/application/RequestProductionAccessSuccessView.scala.html
> +                    content = Text(apis.head.apiName)
Could you have a chat with Jonathon about adding multiple APIs? Perhaps in that scenario we should display all the API names. Perhaps add that as a UI improvement ticket?

2023-11-27 12:46 UTC, PaulCDurham commented on app/views/application/RequestProductionAccessSuccessView.scala.html
> +                    content = Text(apis.head.apiName)
I see you've done that, cool

2023-11-27 13:18 UTC, PaulCDurham approved these changes

2023-11-27 13:41 UTC, PaulCDurham approved these changes

2023-11-27 13:41 UTC, merged