Hipp 1355 my apis page
hmrc/api-hub-frontend pull request #274
Opened 2024-07-08 12:06 UTC by llmikeyj

2024-07-08 14:28 UTC, rdawson-hmrc requested changes

2024-07-08 14:28 UTC, rdawson-hmrc commented on app/views/myapis/MyApisView.scala.html
> +    pageTitle = titleNoForm(messages("govuk-grid-column-two-thirds.title")),
wrong page title!

2024-07-08 14:28 UTC, rdawson-hmrc commented on app/views/myapis/MyApisView.scala.html
> +    activeLink = Some("apiHubAdmin"),
Is this right? The user might not be an admin

2024-07-08 14:28 UTC, rdawson-hmrc commented on app/views/myapis/MyApisView.scala.html
> +    @messages("myApis.all.heading", myApis.size)
I think the number of APIs should be dynamic so it changes when you start filtering (this is how the other pages work)

2024-07-08 14:28 UTC, rdawson-hmrc commented on app/assets/javascripts/myApis.js
> +                elSearchResultsSize.textContent = count;
I get JS errors from this line, there is no element with id='searchResultsSize'

2024-07-08 14:28 UTC, rdawson-hmrc commented on app/assets/javascripts/myApis.js
> +        // view.toggleNoResultsPanel(model.resultCount === 0);
Remove commented code

2024-07-08 14:28 UTC, rdawson-hmrc commented on app/assets/javascripts/myApis.js
> +        console.log(paginationDetails)
Remove debug logging

2024-07-08 14:28 UTC, rdawson-hmrc commented on jsTest/tests/myApis.spec.js
> +    function getVisiblePanelData(...props) {
This duplicates getMyApisVisiblePanelData() above

2024-07-08 14:28 UTC, rdawson-hmrc commented on jsTest/tests/myApis.spec.js
> +        console.log("OIYAF")
Remove debug logging

2024-07-08 14:28 UTC, rdawson-hmrc commented on test/controllers/myapis/MyApisControllerSpec.scala
> +        status(result) mustEqual SEE_OTHER
Is this right? When I visit the page as a user with no APIs I still see the Your APIs page

2024-07-08 14:28 UTC, rdawson-hmrc commented on test/controllers/myapis/MyApisControllerSpec.scala
> +  "GET" - {
There's something odd about this test class, the tests don't seem to actually run. If I change one of assertions so that it should fail the build still passes

2024-07-08 14:45 UTC, rdawson-hmrc commented on app/views/myapis/MyApisView.scala.html
> +    <div class="gem-c-search__item-wrapper">
We are missing the 'Filter by API name' heading shown in the ticket. Also should probably have a bit more space between the search box and the first result

2024-07-08 15:38 UTC, llmikeyj commented on test/controllers/myapis/MyApisControllerSpec.scala
> +        status(result) mustEqual SEE_OTHER
Whitney mentioned that the dashboard page which links to this page would not display the link if either of the scenarios (no apis, or no teams) are in play.

2024-07-09 05:47 UTC, llmikeyj commented on test/controllers/myapis/MyApisControllerSpec.scala
> +        status(result) mustEqual SEE_OTHER
I've dropped back in an error page for that scenario for now.

2024-07-09 07:50 UTC, rdawson-hmrc approved these changes

2024-07-09 07:50 UTC, rdawson-hmrc commented on test/controllers/myapis/MyApisControllerSpec.scala
> +        contentAsString(result) must include("You have no APIs, or do do not belong to any teams.")
minor typo here 'do do not'

2024-07-09 08:26 UTC, rdawson-hmrc approved these changes

2024-07-09 08:41 UTC, merged