HIPP-1371: Rewire change api team to go via applications
hmrc/api-hub-frontend pull request #282
Opened 2024-07-22 15:50 UTC by llmikeyj

2024-07-23 10:03 UTC, PaulCDurham requested changes

2024-07-23 10:03 UTC, PaulCDurham commented on app/connectors/ApplicationsConnector.scala
> +      }
The controller can return 404 Not Found - could we add support and a test for that?

2024-07-25 08:36 UTC, PaulCDurham requested changes

2024-07-25 08:36 UTC, PaulCDurham commented on app/connectors/ApplicationsConnector.scala
> +        case Left(e) if e.statusCode == NOT_FOUND => Future.successful(Right())
Maybe change the return signature to Option[Unit] and return None for Not Found? At the moment this is returning success when the BE says failure. No Left value is ever returned.

2024-07-25 08:41 UTC, llmikeyj commented on app/connectors/ApplicationsConnector.scala
> +        case Left(e) if e.statusCode == NOT_FOUND => Future.successful(Right())
Maybe. I think the issue is though that we don't have a defined use case for this scenario. All of the other connectors ignore Not Founds I think, so that the FE keeps going.

2024-07-25 08:50 UTC, PaulCDurham commented on app/connectors/ApplicationsConnector.scala
> +        case Left(e) if e.statusCode == NOT_FOUND => Future.successful(Right())
This is from getApplication:
`case Left(e) if e.statusCode==404 => Future.successful(None)`

The controller should probably show an error page with a message like "API or Team not found".

There should be ACs for this really but they're missing.

2024-07-26 07:45 UTC, PaulCDurham commented on app/connectors/ApplicationsConnector.scala
> +  def updateApiTeam(apiId: String, teamId: String)(implicit hc: HeaderCarrier): Future[Either[ApplicationsException, Option[Unit]]] = {
Just Future[Option[Unit]]? The code doesn't return a Left value so the Either is redundant.

2024-07-26 08:09 UTC, llmikeyj commented on app/connectors/ApplicationsConnector.scala
> +        case Left(e) if e.statusCode == NOT_FOUND => Future.successful(Right())
Done

2024-07-26 08:28 UTC, llmikeyj commented on app/connectors/ApplicationsConnector.scala
> +  def updateApiTeam(apiId: String, teamId: String)(implicit hc: HeaderCarrier): Future[Either[ApplicationsException, Option[Unit]]] = {
Ok

2024-07-26 08:33 UTC, PaulCDurham approved these changes

2024-07-26 08:40 UTC, merged