HIPP-1166: Remove member from team screens
hmrc/api-hub-frontend pull request #295
Opened 2024-08-06 20:33 UTC by victorarbuesmallada

2024-08-06 20:55 UTC, victorarbuesmallada commented on conf/team.routes
> +GET     /remove-team-member/:teamMemberIndex/team/:id       controllers.team.RemoveTeamMemberController.removeTeamMemberFromExistingTeam(id: String, teamMemberIndex: Int)
I'm thinking that the encrypted email is probably a better option than the member index within a team.
I went with the index since that's what we use in the other [remove-team-member endpoint](https://github.com/hmrc/api-hub-frontend/pull/295/files#diff-0404f2d0b09fc6f9f341726b74d801a6cebd3bedec306a05aaf4b9f0034768f5R6).
Happy to change it.

2024-08-07 12:10 UTC, victorarbuesmallada commented on conf/team.routes
> +GET     /remove-team-member/:teamMemberIndex/team/:id       controllers.team.RemoveTeamMemberController.removeTeamMemberFromExistingTeam(id: String, teamMemberIndex: Int)
after speaking with Paul, we decided to go with the encrypted email

2024-08-07 13:22 UTC, victorarbuesmallada commented on package-lock.json
> -      "version": "8.17.0",
dependabot was complaining and ran `npm audit fix` to deal with it, happy to revert this back.

2024-08-07 16:09 UTC, PaulCDurham requested changes
The main thing to change is to remove the back link from the success page. The Jira tickets usually tell us when to exclude the back link but that is missing off HIPP-1166.

2024-08-07 16:09 UTC, PaulCDurham commented on app/views/team/RemoveTeamMemberSuccessView.scala.html
> +@layout(pageTitle = titleNoForm(messages("manageTeam.removeTeamMember.success.title", team.name)), user = Some(user)) {
A success view should not have the back link as that effectively tries to undo the removal.

2024-08-08 07:58 UTC, PaulCDurham approved these changes

2024-08-08 08:27 UTC, merged