Hipp 260 add scopes frontend
hmrc/api-hub-frontend pull request #30
Opened 2023-02-10 11:42 UTC by llmikeyj

2023-02-10 15:22 UTC, laurahk commented on app/connectors/ApplicationsConnector.scala
> +  def requestAdditionalScope(id: String, newScope: NewScope)(implicit hc: HeaderCarrier): Future[Unit] = {
like the name of this method 👍

2023-02-10 15:32 UTC, laurahk commented on app/services/ApiHubService.scala
> +
Needs associated tests in `ApiHubServiceSpec`

2023-02-10 15:38 UTC, laurahk commented on app/controllers/AddScopeController.scala
> +        case Some(application) => Ok(view(application.id, form))
This is my lack of knowledge in this area, but when you load the addScopes page, is this piece of code passing through the applicationID to the form, so that when the form is submitted, we can send the appID in the post request?

2023-02-10 15:40 UTC, laurahk requested changes
Ran it up and it all looks good to me 😄 
Just some additional tests to add I think.

2023-02-10 15:42 UTC, PaulCDurham submitted a review, later dismissed
Just ran it and had a play. Works a treat. It's good to see how you got all the Form stuff working with checkboxes.

2023-02-10 15:42 UTC, PaulCDurham commented on app/connectors/ApplicationsConnector.scala
> +
Could you please add an integration test to `ApplicationsConnectorSpec`? These are the Wiremock tests we have that serve as unit tests for this class.

2023-02-10 15:42 UTC, PaulCDurham commented on app/controllers/AddScopeController.scala
> +            application => Redirect(routes.RequestScopeSuccessController.onPageLoad(id)))
As `requestAdditionalScope` returns `Future[Unit]]` I think it would be stylistically better to use `_ =>` rather than `application =>`. The application bit had me slightly confused as to why we weren't using it.

2023-02-10 15:42 UTC, PaulCDurham commented on test/controllers/AddScopeControllerSpec.scala
> +    "must register the scope and redirect to the Index page when valid" in {
I don't think it redirects to Index, could you fix this text?

2023-02-10 15:42 UTC, PaulCDurham commented on app/views/AddScopeView.scala.html
> +
As mentioned, could you add a `user: Option[UserModel]` parameter, pass that in from the controller, and pass it on to layout?

2023-02-13 10:41 UTC, llmikeyj commented on app/connectors/ApplicationsConnector.scala
> +
Ok done

2023-02-13 11:17 UTC, llmikeyj commented on app/services/ApiHubService.scala
> +
Ok, done

2023-02-13 11:18 UTC, llmikeyj commented on test/controllers/AddScopeControllerSpec.scala
> +    "must register the scope and redirect to the Index page when valid" in {
Ok, done

2023-02-13 11:21 UTC, llmikeyj commented on app/controllers/AddScopeController.scala
> +            application => Redirect(routes.RequestScopeSuccessController.onPageLoad(id)))
Ok

2023-02-13 11:21 UTC, llmikeyj commented on test/controllers/AddScopeControllerSpec.scala
> +    "must register the scope and redirect to the Index page when valid" in {
Ok

2023-02-13 11:50 UTC, llmikeyj commented on app/views/AddScopeView.scala.html
> +
Ok, done

2023-02-13 11:51 UTC, llmikeyj commented on app/controllers/AddScopeController.scala
> +        case Some(application) => Ok(view(application.id, form))
It is, yes,

2023-02-13 14:37 UTC, laurahk commented on it/connectors/ApplicationsConnectorSpec.scala
> +  }
Thanks for these tests - only the failure scenario missing but I think that's ok for the sake of getting the ticket merged :)

2023-02-13 14:44 UTC, laurahk approved these changes

2023-02-13 14:51 UTC, merged