HIPP-1549: Banner fixes
hmrc/api-hub-frontend pull request #395
Opened 2024-10-09 17:42 UTC by llmikeyj

2024-10-10 08:15 UTC, victorarbuesmallada commented on app/views/application/ApplicationAccessRequestsView.scala.html
> +    accessRequests.count(_.status == Pending)
not sure if you would prefer to use exists instead
```suggestion
    accessRequests.exists(_.status == Pending)
```

2024-10-10 08:17 UTC, victorarbuesmallada approved these changes

2024-10-10 08:23 UTC, PaulCDurham requested changes

2024-10-10 08:23 UTC, PaulCDurham commented on app/controllers/helpers/ApplicationApiBuilder.scala
> +  def build(application: Application)(implicit request: Request[?]): Future[(Seq[ApplicationApi], Int)] = {
You're kind of binding a generic component to specific UI usage. If you have to do it this way at least use a case class rather than a tuple. The method return of `Future[(Seq[ApplicationApi], Int)]` gives no indication of what the `Int` is.

Maybe add a utility method to the companion object for ApplicationApi that can give you just the Int? That would be cleaner.

2024-10-11 08:26 UTC, PaulCDurham approved these changes

2024-10-11 08:26 UTC, merged