HIPP-1591: Validate OAS document on submission
hmrc/api-hub-frontend pull request #402
Opened 2024-10-14 14:18 UTC by victorarbuesmallada

2024-10-14 14:19 UTC, victorarbuesmallada commented on project/AppDependencies.scala
> +    "io.swagger.parser.v3" % "swagger-parser" % "2.1.20"
needed to go back a bit cause I was getting a method not found error
```
2024-10-14 10:57:07,108 level=[ERROR] logger=[org.apache.pekko.actor.ActorSystemImpl] thread=[application-pekko.actor.default-dispatcher-11] rid=[] user=[] message=[Uncaught error from thread [application-pekko.actor.default-dispatcher-9]: 'void com.fasterxml.jackson.dataformat.yaml.YAMLParser.createChildObjectContext(int, int)', shutting down JVM since 'pekko.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]] exception=[java.lang.NoSuchMethodError: 'void com.fasterxml.jackson.dataformat.yaml.YAMLParser.createChildObjectContext(int, int)'
        at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:520)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4759)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3124)
        at io.swagger.v3.parser.util.DeserializationUtils.readYamlTree(DeserializationUtils.java:279)
        at io.swagger.v3.parser.util.DeserializationUtils.deserializeIntoTree(DeserializationUtils.java:172)
        at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:170)
        at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:107)
        at models.curl.OpenApiDoc$.$anonfun$4(OpenApiDoc.scala:100)
        at scala.util.Try$.apply(Try.scala:217)
        at models.curl.OpenApiDoc$.parse(OpenApiDoc.scala:100)
        at controllers.myapis.produce.ProduceApiEnterOasController.validateOAS(ProduceApiEnterOasController.scala:80)
        at controllers.myapis.produce.ProduceApiEnterOasController.onSubmit$$anonfun$1$$anonfun$2(ProduceApiEnterOasController.scala:68)
        at play.api.data.Form.fold(Form.scala:176)
        at controllers.myapis.produce.ProduceApiEnterOasController.onSubmit$$anonfun$1(ProduceApiEnterOasController.scala:67)
        at scala.util.Either.fold(Either.scala:197)
        at play.api.mvc.ActionRefiner.invokeBlock$$anonfun$3(Action.scala:533)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
        at org.apache.pekko.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:73)
        at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run$$anonfun$1(BatchingExecutor.scala:110)
        at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run$$anonfun$adapted$1(BatchingExecutor.scala:119)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:119)
        at org.apache.pekko.dispatch.TaskInvocation.run(AbstractDispatcher.scala:59)
        at uk.gov.hmrc.play.bootstrap.dispatchers.MDCPropagatingExecutorService.execute$$anonfun$1(MDCPropagatingExecutorService.scala:53)
        at org.apache.pekko.dispatch.ForkJoinExecutorConfigurator$PekkoForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:57)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```
Hopefully our bootstrap/play dependencies will include newer jackson libraries soon

2024-10-15 07:01 UTC, rdawson-hmrc commented on app/controllers/myapis/produce/ProduceApiEnterOasController.scala
> +  private def validateOAS(oas: String)(implicit messagesProvider: MessagesProvider): Either[String, Unit] =
I don't think this is what the ticket is asking for, it says we should use the APIM endpoint for validation not the swagger library?

2024-10-15 07:02 UTC, rdawson-hmrc requested changes
I think we should use the APIM endpoint for validation not a local swagger library

2024-10-15 16:07 UTC, llmikeyj commented on project/AppDependencies.scala
> +    "io.swagger.parser.v3" % "swagger-parser" % "2.1.20"
Do we still need the downgraded version?

2024-10-16 08:49 UTC, PaulCDurham requested changes

2024-10-16 08:49 UTC, PaulCDurham commented on app/connectors/ApplicationsConnector.scala
> +  def validateOAS(oas: String)(implicit hc: HeaderCarrier): Future[Either[InvalidOasResponse, Unit]] = {
The signature needs thinking about. The Left response should be some exception type. That indicates the call failed or was invalid. The Right response should cover both "it's valid" and "it's not valid and here's some reasons why." Consider adding a case class that can indicate validity and hold invalid reasons.

Look at how the backend handles this for an example.

2024-10-16 08:49 UTC, PaulCDurham commented on app/controllers/myapis/produce/ProduceApiEnterOasController.scala
> +              Future.successful(BadRequest(view(boundedForm.withGlobalError(error), mode))),
The idea was to simply respond with the errors in JSON. Nothing fancy. No UI. We want to experiment with this response to see how we can interpret it for the user.

Use something like BadRequest(Json.prettyPrint(Json.toJson(InvalidOasResponse))). (That's just a guess and won't compile)

2024-10-16 08:49 UTC, PaulCDurham commented on app/models/curl/OpenApiDoc.scala
>  }
Why is this file changing? It has nothing to do with the Jira ticket.

2024-10-16 08:49 UTC, PaulCDurham commented on app/models/requests/OASValidateRequest.scala
> +}
Do we need a case class to wrap a string in JSON? Maybe just use another content type such as YAML that better represents what we're passing to the backend.

2024-10-16 08:49 UTC, PaulCDurham commented on app/services/CurlCommandService.scala
>          api <- application.apis
Why is this file changing?

2024-10-16 08:49 UTC, PaulCDurham commented on app/viewmodels/govuk/ErrorSummaryFluency.scala
> +            content = HtmlContent(messages(error.message, error.args*))
Why do we need HTML content?

2024-10-16 08:49 UTC, PaulCDurham commented on build.sbt
> +    )
Why do we need to do this? There is a clear risk we'll update the entries in the dependencies file and expect that to work.

2024-10-16 09:23 UTC, victorarbuesmallada commented on app/services/CurlCommandService.scala
>          api <- application.apis
OpenApiDoc is getting the error message from the messages file

2024-10-16 09:24 UTC, victorarbuesmallada commented on app/viewmodels/govuk/ErrorSummaryFluency.scala
> +            content = HtmlContent(messages(error.message, error.args*))
I was passing a message that contained html elements in previous commits, don't need it now

2024-10-16 09:39 UTC, victorarbuesmallada commented on app/connectors/ApplicationsConnector.scala
> +            Future.failed(UpstreamErrorResponse("Unexpected response", response.status))
ah right, sorry I got the idea from this [line](https://github.com/hmrc/api-hub-frontend/pull/402/files#diff-20709fb67e6acab3898727f17fa377f3d9d24b068dccc58d797401dd860b0a38R588), will amend that now

2024-10-16 15:28 UTC, llmikeyj submitted a review, later dismissed

2024-10-17 07:06 UTC, rdawson-hmrc approved these changes

2024-10-17 08:19 UTC, PaulCDurham requested changes

2024-10-17 08:19 UTC, PaulCDurham commented on app/connectors/ApplicationsConnector.scala
> +  def validateOAS(oas: String)
Sorry, I got this completely wrong with the previous review. I got mixed up between the frontend and backend. I think the signature we want here is:
`def validateOas(oas: String)(implicit hc: HeaderCarrier): Future[Either[FailuresResponse, Unit]]`

Or `InvalidOasResponse` would work too in place of `FailuresResponse`.

We should use `Future.failed` for unexpected responses. `ApplicationsException` is a backend pattern.

My bad.

2024-10-17 08:19 UTC, PaulCDurham commented on app/models/deployment/FailuresResponse.scala
> +  def errorMessage(): String =
I don't think we should have the error message in the model as it's a UI thing. We'll change that soon anyway and display the failures structure to the user in some more meaningful way.

2024-10-17 08:19 UTC, PaulCDurham commented on app/connectors/ApplicationsConnector.scala
> +                             OASException.forError(r.failure.errorMessage())
Before we return Left(FailuresResponse or InvalidOasResponse) could we please log this at WARN level? Pretty print the JSON in the log entry. I think that might help with some diagnostics in the future if we're not provided with screen shots by the user.

2024-10-17 11:58 UTC, victorarbuesmallada commented
test this please

2024-10-17 14:17 UTC, PaulCDurham approved these changes

2024-10-17 14:17 UTC, merged