HIPP-1606: Use API name from OAS file in the review screen
hmrc/api-hub-frontend pull request #412
Opened 2024-10-18 11:22 UTC by victorarbuesmallada

2024-10-18 14:01 UTC, PaulCDurham requested changes

2024-10-18 14:01 UTC, PaulCDurham commented on app/models/curl/OpenApiDoc.scala
> +
I don't think we should have an error message here. That's a UI thing. Return Option[String]? Let the calling code decide what to do when it's None.

2024-10-18 14:08 UTC, victorarbuesmallada commented on app/controllers/myapis/produce/ProduceApiEnterOasController.scala
> +import models.curl.OpenApiDoc
I did have that on the previous commit, will revert this commit to have that in place

2024-10-21 12:46 UTC, PaulCDurham approved these changes

2024-10-21 12:47 UTC, merged