HIPP-1615: Adopt new APIM deployment statuses
hmrc/api-hub-frontend pull request #422
Opened 2024-10-24 11:39 UTC by victorarbuesmallada

2024-10-24 11:44 UTC, victorarbuesmallada commented on test/controllers/myapis/ApiUsageControllerSpec.scala
> -import org.mockito.ArgumentMatchers.{any, eq as eqTo}
IntelliJ messes up with `as` whenever it needs to deal with imports, but it's fine with `=>`

2024-10-24 15:51 UTC, victorarbuesmallada commented on app/models/api/ApiDeploymentStatuses.scala
> +    ((__ \ "_type").read[String]
the `_type`  has a different package in the backend and needed to do this to get around that.

2024-10-25 14:18 UTC, PaulCDurham requested changes

2024-10-25 14:18 UTC, PaulCDurham commented on app/controllers/myapis/MyApiDetailsController.scala
> +      team <- request.apiDetails.teamId.flatTraverse(apiHubService.findTeamById)
Do we need Cats for this? Remember not everybody knows it. If it gives us something useful like EitherT then Ok but I don't see what value this method is adding.

2024-10-25 14:18 UTC, PaulCDurham commented on app/controllers/myapis/MyApiDetailsController.scala
> +      team <- request.apiDetails.teamId.flatTraverse(apiHubService.findTeamById)
Also, this is ignoring the case where the team is not found. Maybe look at the very similar ApiDetailsController and how that handles teams.

Maybe abstract a common way of handling an optional team Id to optional text and add that to the Fetching trait.

2024-10-29 16:10 UTC, PaulCDurham approved these changes

2024-10-29 17:29 UTC, merged