HIPP-1636: Hide 'Cancel request' button when the access request is no…
hmrc/api-hub-frontend pull request #438
Opened 2024-11-07 14:34 UTC by victorarbuesmallada

…t on 'Pending' state and the user does not belong to the application team

2024-11-07 14:39 UTC, llmikeyj requested changes
I think we need one more test case, which is that even if you are an approver, you cannot cancel the request when you are not a team member?

2024-11-07 16:30 UTC, victorarbuesmallada commented on app/controllers/application/AccessRequestController.scala
> +            .invokeBlock(request, implicit applicationRequest => Future.successful(buildView(accessRequest)))
this endpoint doesn't take an application id as parameter, so I needed to use the action builder like this

2024-11-07 16:44 UTC, victorarbuesmallada commented
> I think we need one more test case, which is that even if you are an approver, you cannot cancel the request when you are not a team member?

The logic behind this ticket has changed and is now about hiding the button only if the screen is on the *admin* side of the service.

2024-11-08 13:09 UTC, PaulCDurham approved these changes

2024-11-08 14:11 UTC, merged