HIPP-1674 - Update API start controller
hmrc/api-hub-frontend pull request #447
Opened 2024-11-13 17:19 UTC by victorarbuesmallada

2024-11-13 17:23 UTC, victorarbuesmallada commented on app/controllers/myapis/update/UpdateApiStartController.scala
> +        updatedAnswers <- updateAnswer(userAnswers, UpdateApiApiPage, deploymentDetails)
not sure what to do with this one, should I check the answers for `UpdateApiApiPage` before pulling the deployment details?

2024-11-14 10:59 UTC, PaulCDurham requested changes

2024-11-14 10:59 UTC, PaulCDurham commented on app/controllers/myapis/update/UpdateApiStartController.scala
> +        errorResultBuilder.apiNotFoundInApim(apiDetail)
We don't handle exceptions in controllers. Let the error handler do that to make sure things like consistent logging take place.

2024-11-14 10:59 UTC, PaulCDurham commented on app/controllers/myapis/update/UpdateApiStartController.scala
> +          .leftMap(e => errorResultBuilder.internalServerError(e))
We don't handle exceptions in controllers. Let the error handler do that to make sure things like consistent logging take place.

2024-11-14 10:59 UTC, PaulCDurham commented on app/models/myapis/ApiDomainSubdomain.scala
> +case class ApiDomainSubdomain(domain: String, subDomain: String)
Why rename it? If you want to make it common then we need to define how we want to do that and implement that across all types.

2024-11-14 10:59 UTC, PaulCDurham commented on test/controllers/myapis/update/UpdateApiStartControllerSpec.scala
> +      }
Could you add assertions on the actual message and check the page is valid HTML?

2024-11-14 10:59 UTC, PaulCDurham commented on test/controllers/myapis/update/UpdateApiStartControllerSpec.scala
> +        status(result) mustBe NOT_FOUND
Could you add assertions on the actual message and check the page is valid HTML?

2024-11-14 10:59 UTC, PaulCDurham commented on test/controllers/myapis/update/UpdateApiStartControllerSpec.scala
> +    "must return a 500 if there is an error while saving the answers" in {
We don't typically test 500s. That's the responsibility of the error handler.

2024-11-14 11:31 UTC, victorarbuesmallada commented on app/models/myapis/ApiDomainSubdomain.scala
> +case class ApiDomainSubdomain(domain: String, subDomain: String)
I did that before the chat we had this morning, will revert it back

2024-11-14 14:47 UTC, PaulCDurham approved these changes

2024-11-14 14:48 UTC, merged