HIPP-1755: Add fetch credentials logic on the environment page
hmrc/api-hub-frontend pull request #477
Opened 2024-12-06 17:36 UTC by victorarbuesmallada

2024-12-06 18:00 UTC, victorarbuesmallada commented
test this please

2024-12-09 13:38 UTC, victorarbuesmallada commented on app/views/application/EnvironmentsView.scala.html
> +        @if(hipEnvironment.isProductionLike && maybeCredentials.isEmpty) {
not sure if I need this condition here
`hipEnvironment.isProductionLike`

2024-12-09 15:16 UTC, PaulCDurham requested changes
The main thing is to always show credentials. If there is an error fetching them then show the obfuscated secret fragment.

2024-12-09 16:44 UTC, llmikeyj approved these changes

2024-12-09 18:33 UTC, victorarbuesmallada commented
test this please

2024-12-10 09:31 UTC, PaulCDurham approved these changes

2024-12-10 09:35 UTC, merged