hipp-400: as per prototype v5
hmrc/api-hub-frontend pull request #64
Opened 2023-04-05 12:08 UTC by tigdik

2023-04-05 14:04 UTC, PaulCDurham requested changes
I think we need to change the ApplicationsConnector to fetch only the applications in which the current user is a team member. At the moment it fetches all applications. I believe HIPP-399 created the endpoint to call.

2023-04-05 15:24 UTC, laurahk commented on app/controllers/IndexController.scala
> +    def createApplication: Action[AnyContent] = identify.async { implicit request =>
As discussed earlier, I don't believe we want both a POST and a GET for this behaviour so I think remove onSubmit method as Paul suggested.

2023-04-05 15:24 UTC, laurahk commented on conf/app.routes
>  POST        /                                                   controllers.IndexController.onSubmit
So you'll need to remove this line too

2023-04-11 08:39 UTC, tigdik commented on app/controllers/IndexController.scala
> +    def createApplication: Action[AnyContent] = identify.async { implicit request =>
fixed

2023-04-11 13:17 UTC, tigdik commented on app/controllers/IndexController.scala
> +    def createApplication: Action[AnyContent] = identify.async { implicit request =>
Factored out to private method

2023-04-11 14:52 UTC, PaulCDurham commented on app/connectors/ApplicationsConnector.scala
> +  def getUserApplications(userEmail:String)(implicit hc: HeaderCarrier): Future[Seq[Application]] = {
Needs a test in ApplicationsConnectorSpec

2023-04-11 14:52 UTC, PaulCDurham commented on app/services/ApiHubService.scala
> +    logger.debug(s"Retrieving applications for user '$email'")
We can't log emails for the same reason we can't use them in URLs.

2023-04-11 15:25 UTC, PaulCDurham requested changes
We need to add the email address encryption key to config. That will also need to be added in higher environments too.

2023-04-11 16:00 UTC, laurahk commented on conf/app.routes
>  POST        /                                                   controllers.IndexController.onSubmit
I said this because I thought we agreed last week that we were getting rid of the POST endpoint all together and replacing it with a GET. So the button and the link would both be a GET.

2023-04-11 16:04 UTC, tigdik commented on app/connectors/ApplicationsConnector.scala
> +    val emailEncrypted = crypto.QueryParameterCrypto.encrypt(PlainText(userEmail)).value
it is done automatically by RequestBuilder next line down

2023-04-11 16:05 UTC, laurahk commented on test/controllers/IndexControllerSpec.scala
> +        Application("id-2", "app-name-2", Creator("creator-email-2"), Seq.empty).copy(teamMembers = Seq(TeamMember("test-email")))
You don't need to copy the application again, you can use the last parameter to set the team members:
```Application("id-1", "app-name-1", Creator("creator-email-2"), Seq(TeamMember("test-email")))```
Or is there a reason you've copied it?

Also extracted "test-email" out as a `val` would help to see where it's used and why.

2023-04-11 16:07 UTC, laurahk commented on app/controllers/IndexController.scala
> +  def onSubmit: Action[AnyContent] = identify.async { implicit request => createUserApplication }
As I say in another comment below, I thought we had decided to have a GET, not a GET and a POST. However, the code is abstracted so I think it's fine to leave this as is 👍

2023-04-11 16:26 UTC, tigdik commented on test/controllers/IndexControllerSpec.scala
> +        Application("id-2", "app-name-2", Creator("creator-email-2"), Seq.empty).copy(teamMembers = Seq(TeamMember("test-email")))
Application creates teamMembers as empty collection no matter what you supply to its constructor. Check the Application def apply(...)

2023-04-11 16:40 UTC, tigdik commented on app/controllers/IndexController.scala
> +  def onSubmit: Action[AnyContent] = identify.async { implicit request => createUserApplication }
This is what Paul suggested in his comments. With regards to having only GET - we need then to convert "create Application" button to a link which is not a hmrc component

2023-04-11 17:39 UTC, tigdik commented
> We need to add the email address encryption key to config. That will also need checking in higher environments too but I believe might be there. Check all the app-config-xxx repos for queryParameter.encryption.key.

fixed

2023-04-12 11:19 UTC, merged